Fix installation when gitops/pipelines is not activated

diff --git a/test/data/helm-chart/template.yaml b/test/data/helm-chart/template.yaml
--- a/test/data/helm-chart/template.yaml
+++ b/test/data/helm-chart/template.yaml
@@ -379,7 +379,7 @@ spec:
               yq --inplace '. *= load("rhtap-values.yaml")' "${HELM_VALUES}"
               echo -n "."
               KUBERNETES_CLUSTER_FQDN="$(
-                kubectl get routes -n openshift-pipelines pipelines-as-code-controller -o jsonpath='{.spec.host}' | \
+                kubectl get routes -n openshift-console console -o jsonpath='{.spec.host}' | \
                 cut -d. -f 2-
               )"
               export KUBERNETES_CLUSTER_FQDN
@@ -525,6 +525,7 @@ spec:
         
         
                 
+        
         - name: configure-gitops
           image: "registry.redhat.io/openshift4/ose-tools-rhel8:latest"
           workingDir: /tmp
@@ -830,7 +831,9 @@ spec:
               echo
               echo "Configuration successful"
         
+        
                 
+        
         - name: configure-namespace
           image: "registry.redhat.io/openshift4/ose-tools-rhel8:latest"
           workingDir: /tmp
@@ -1200,7 +1203,9 @@ spec:
               echo
               echo "Configuration successful"
         
+        
                 
+        
         - name: configure-pipelines
           image: quay.io/redhat-appstudio/appstudio-utils:dbbdd82734232e6289e8fbae5b4c858481a7c057
           workingDir: /tmp
@@ -1326,6 +1331,7 @@ spec:
         
               echo
               echo "Configuration successful"
+        
         
                 
         
@@ -1696,7 +1702,8 @@ spec:
       automountServiceAccountToken: true
       containers:
                 
-        - name: test-namespace
+        
+        - name: test-developer-hub
           image: "registry.redhat.io/openshift4/ose-tools-rhel8:latest"
           workingDir: /tmp
           command:
@@ -1707,55 +1714,22 @@ spec:
               set -o nounset
               set -o pipefail
             
+              EXIT_CODE=0
         
-              pipeline_id="$(cat << EOF | kubectl create -f - | cut -d' ' -f 1
-                      
-                apiVersion: tekton.dev/v1
-                kind: PipelineRun
-                metadata:
-                  generateName: rhtap-test-config-
-                  annotations:
-                    helm.sh/chart: "redhat-trusted-application-pipeline-0.14.1"
-                spec:
-                  pipelineSpec:
-                    tasks:
-                    - name: argocd-login-check
-                      taskRef:
-                        resolver: cluster
-                        params:
-                          - name: kind
-                            value: task
-                          - name: name
-                            value: argocd-login-check
-                          - name: namespace
-                            value: rhtap
-                
-              EOF
-              )"
-              echo -n "* Pipeline $pipeline_id: "
-              while ! kubectl get "$pipeline_id" | grep --extended-regex --quiet " False | True "; do
-                echo -n "."
-                sleep 2
-              done
-              if kubectl get "$pipeline_id" | grep --quiet " True "; then
-                kubectl delete "$pipeline_id" > /dev/null
-                echo "OK"
+              echo -n "* UI: "
+              HOSTNAME="$(kubectl get routes "redhat-developer-hub" -o jsonpath="{.spec.host}")"
+              if ! curl --fail --insecure --location --output /dev/null --silent "https://$HOSTNAME"; then
+                echo "FAIL"
+                EXIT_CODE=1
               else
-                echo "Failed"
-                exit 1
+                echo "OK"
               fi
         
-              echo
-              echo "Test successful"
-          resources:
-            limits:
-              cpu: 100m
-              memory: 256Mi
-            requests:
-              cpu: 20m
-              memory: 128Mi
+              exit $EXIT_CODE
+        
         
                 
+        
         - name: test-gitops
           image: "registry.redhat.io/openshift4/ose-tools-rhel8:latest"
           workingDir: /tmp
@@ -1864,7 +1838,71 @@ spec:
               cpu: 20m
               memory: 128Mi
         
+        
                 
+        
+        - name: test-namespace
+          image: "registry.redhat.io/openshift4/ose-tools-rhel8:latest"
+          workingDir: /tmp
+          command:
+            - /bin/bash
+            - -c
+            - |
+              set -o errexit
+              set -o nounset
+              set -o pipefail
+            
+        
+              pipeline_id="$(cat << EOF | kubectl create -f - | cut -d' ' -f 1
+                      
+                apiVersion: tekton.dev/v1
+                kind: PipelineRun
+                metadata:
+                  generateName: rhtap-test-config-
+                  annotations:
+                    helm.sh/chart: "redhat-trusted-application-pipeline-0.14.1"
+                spec:
+                  pipelineSpec:
+                    tasks:
+                    - name: argocd-login-check
+                      taskRef:
+                        resolver: cluster
+                        params:
+                          - name: kind
+                            value: task
+                          - name: name
+                            value: argocd-login-check
+                          - name: namespace
+                            value: rhtap
+                
+              EOF
+              )"
+              echo -n "* Pipeline $pipeline_id: "
+              while ! kubectl get "$pipeline_id" | grep --extended-regex --quiet " False | True "; do
+                echo -n "."
+                sleep 2
+              done
+              if kubectl get "$pipeline_id" | grep --quiet " True "; then
+                kubectl delete "$pipeline_id" > /dev/null
+                echo "OK"
+              else
+                echo "Failed"
+                exit 1
+              fi
+        
+              echo
+              echo "Test successful"
+          resources:
+            limits:
+              cpu: 100m
+              memory: 256Mi
+            requests:
+              cpu: 20m
+              memory: 128Mi
+        
+        
+                
+        
         - name: test-pipelines
           image: "registry.redhat.io/openshift4/ose-tools-rhel8:latest"
           workingDir: /tmp
@@ -1927,6 +1965,7 @@ spec:
             requests:
               cpu: 20m
               memory: 128Mi
+        
         
                 
         
