Fix installation when gitops/pipelines is not activated

diff --git a/test/data/helm-chart/template.yaml b/test/data/helm-chart/template.yaml
--- a/test/data/helm-chart/template.yaml
+++ b/test/data/helm-chart/template.yaml
@@ -217,17 +217,24 @@ spec:
             
         
               # ArgoCD integration
-              while [ "$(kubectl get secret "$CHART-argocd-secret" --ignore-not-found -o name | wc -l)" != "1" ]; do
-                echo -ne "_"
-                sleep 2
-              done
-              kubectl get secret "$CHART-argocd-secret" -o yaml > argocd_secret.yaml
-              echo -n "."
+              if kubectl get namespace "openshift-gitops" >/dev/null 2>/dev/null; then
+                while [ "$(kubectl get secret "$CHART-argocd-secret" --ignore-not-found -o name | wc -l)" != "1" ]; do
+                  echo -ne "_"
+                  sleep 2
+                done
+                kubectl get secret "$CHART-argocd-secret" -o yaml > argocd_secret.yaml
+                echo -n "."
         
-              ARGOCD_API_TOKEN="$(yq '.data.api-token | @base64d' argocd_secret.yaml)"
-              ARGOCD_HOSTNAME="$(yq '.data.hostname | @base64d' argocd_secret.yaml)"
-              ARGOCD_PASSWORD="$(yq '.data.password | @base64d' argocd_secret.yaml)"
-              ARGOCD_USER="$(yq '.data.user | @base64d' argocd_secret.yaml)"
+                ARGOCD_API_TOKEN="$(yq '.data.api-token | @base64d' argocd_secret.yaml)"
+                ARGOCD_HOSTNAME="$(yq '.data.hostname | @base64d' argocd_secret.yaml)"
+                ARGOCD_PASSWORD="$(yq '.data.password | @base64d' argocd_secret.yaml)"
+                ARGOCD_USER="$(yq '.data.user | @base64d' argocd_secret.yaml)"
+              else
+                ARGOCD_API_TOKEN="unset"
+                ARGOCD_HOSTNAME="https://unset.unset"
+                ARGOCD_PASSWORD="unset"
+                ARGOCD_USER="unset"
+              fi
               cat << _EOF_ >> "$APPCONFIGEXTRA"
               argocd:
                 username: $ARGOCD_USER
@@ -242,11 +249,15 @@ spec:
               _EOF_
         
               # Tekton integration
-              while [ "$(kubectl get secret "$CHART-pipelines-secret" --ignore-not-found -o name | wc -l)" != "1" ]; do
-                echo -ne "_"
-                sleep 2
-              done
-              PIPELINES_PAC_URL="$(kubectl get secret "$CHART-pipelines-secret" -o yaml | yq '.data.webhook-url | @base64d')"
+              if kubectl get namespace "openshift-pipelines" >/dev/null 2>/dev/null; then
+                while [ "$(kubectl get secret "$CHART-pipelines-secret" --ignore-not-found -o name | wc -l)" != "1" ]; do
+                  echo -ne "_"
+                  sleep 2
+                done
+                PIPELINES_PAC_URL="$(kubectl get secret "$CHART-pipelines-secret" -o yaml | yq '.data.webhook-url | @base64d')"
+              else
+                PIPELINES_PAC_URL="https://unset.unset"
+              fi
               yq -i ".integrations.github[0].apps[0].webhookUrl = \"$PIPELINES_PAC_URL\"" "$APPCONFIGEXTRA"
               echo "OK"
         
@@ -347,7 +358,7 @@ spec:
             
               echo -n "."
               KUBERNETES_CLUSTER_FQDN="$(
-                kubectl get routes -n openshift-pipelines pipelines-as-code-controller -o jsonpath='{.spec.host}' | \
+                kubectl get routes -n openshift-console console -o jsonpath='{.spec.host}' | \
                 cut -d. -f 2-
               )"
               export KUBERNETES_CLUSTER_FQDN
@@ -505,6 +516,7 @@ spec:
         
         
                 
+        
         - name: configure-gitops
           image: "registry.redhat.io/openshift4/ose-tools-rhel8:latest"
           workingDir: /tmp
@@ -810,7 +822,9 @@ spec:
               echo
               echo "Configuration successful"
         
+        
                 
+        
         - name: configure-namespace
           image: "registry.redhat.io/openshift4/ose-tools-rhel8:latest"
           workingDir: /tmp
@@ -1174,7 +1188,9 @@ spec:
               echo
               echo "Configuration successful"
         
+        
                 
+        
         - name: configure-pipelines
           image: quay.io/redhat-appstudio/appstudio-utils:dbbdd82734232e6289e8fbae5b4c858481a7c057
           workingDir: /tmp
@@ -1300,6 +1316,7 @@ spec:
         
               echo
               echo "Configuration successful"
+        
         
                 
         
@@ -1670,7 +1687,8 @@ spec:
       automountServiceAccountToken: true
       containers:
                 
-        - name: test-namespace
+        
+        - name: test-developer-hub
           image: "registry.redhat.io/openshift4/ose-tools-rhel8:latest"
           workingDir: /tmp
           command:
@@ -1681,52 +1699,22 @@ spec:
               set -o nounset
               set -o pipefail
             
+              EXIT_CODE=0
         
-              pipeline_id="$(cat << EOF | kubectl create -f - | cut -d' ' -f 1
-                      
-                apiVersion: tekton.dev/v1
-                kind: PipelineRun
-                metadata:
-                  generateName: rhtap-test-config-
-                  annotations:
-                    helm.sh/chart: "redhat-trusted-application-pipeline-0.14.1"
-                spec:
-                  pipelineSpec:
-                    tasks:
-                    - name: argocd-login-check
-                      taskRef:
-                        resolver: cluster
-                        params:
-                          - name: kind
-                            value: task
-                          - name: name
-                            value: argocd-login-check
-                          - name: namespace
-                            value: rhtap
-                
-              EOF
-              )"
-              echo -n "* Pipeline $pipeline_id: "
-              while ! kubectl get "$pipeline_id" | grep --extended-regex --quiet " False | True "; do
-                echo -n "."
-                sleep 2
-              done
-              if kubectl get "$pipeline_id" | grep --quiet " True "; then
-                kubectl delete "$pipeline_id" > /dev/null
-                echo "OK"
+              echo -n "* UI: "
+              HOSTNAME="$(kubectl get routes "redhat-developer-hub" -o jsonpath="{.spec.host}")"
+              if ! curl --fail --insecure --location --output /dev/null --silent "https://$HOSTNAME"; then
+                echo "FAIL"
+                EXIT_CODE=1
               else
-                echo "Failed"
-                exit 1
+                echo "OK"
               fi
-          resources:
-            limits:
-              cpu: 100m
-              memory: 256Mi
-            requests:
-              cpu: 20m
-              memory: 128Mi
+        
+              exit $EXIT_CODE
+        
         
                 
+        
         - name: test-gitops
           image: "registry.redhat.io/openshift4/ose-tools-rhel8:latest"
           workingDir: /tmp
@@ -1833,7 +1821,68 @@ spec:
               cpu: 20m
               memory: 128Mi
         
+        
                 
+        
+        - name: test-namespace
+          image: "registry.redhat.io/openshift4/ose-tools-rhel8:latest"
+          workingDir: /tmp
+          command:
+            - /bin/bash
+            - -c
+            - |
+              set -o errexit
+              set -o nounset
+              set -o pipefail
+            
+        
+              pipeline_id="$(cat << EOF | kubectl create -f - | cut -d' ' -f 1
+                      
+                apiVersion: tekton.dev/v1
+                kind: PipelineRun
+                metadata:
+                  generateName: rhtap-test-config-
+                  annotations:
+                    helm.sh/chart: "redhat-trusted-application-pipeline-0.14.1"
+                spec:
+                  pipelineSpec:
+                    tasks:
+                    - name: argocd-login-check
+                      taskRef:
+                        resolver: cluster
+                        params:
+                          - name: kind
+                            value: task
+                          - name: name
+                            value: argocd-login-check
+                          - name: namespace
+                            value: rhtap
+                
+              EOF
+              )"
+              echo -n "* Pipeline $pipeline_id: "
+              while ! kubectl get "$pipeline_id" | grep --extended-regex --quiet " False | True "; do
+                echo -n "."
+                sleep 2
+              done
+              if kubectl get "$pipeline_id" | grep --quiet " True "; then
+                kubectl delete "$pipeline_id" > /dev/null
+                echo "OK"
+              else
+                echo "Failed"
+                exit 1
+              fi
+          resources:
+            limits:
+              cpu: 100m
+              memory: 256Mi
+            requests:
+              cpu: 20m
+              memory: 128Mi
+        
+        
+                
+        
         - name: test-pipelines
           image: "registry.redhat.io/openshift4/ose-tools-rhel8:latest"
           workingDir: /tmp
@@ -1893,6 +1942,7 @@ spec:
             requests:
               cpu: 20m
               memory: 128Mi
+        
         
                 
         
